FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache netcat-openbsd mysql-client bash

COPY package*.json ./
COPY prisma ./prisma/

RUN npm install

RUN npx prisma generate

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]